routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index');

Route::group(['middleware'=>['auth']], function (){
    Route::get('/admin', function (){
        return view('admin.index');
    });

    /*projects controller
    consist of
    create
    retrieve
    update
    Delete
    */
    Route::resource('project', 'ProjectController');
    Route::get('/admin/project', 'ProjectController@index');
    Route::get('/admin/project/contact/{id}', 'ProjectController@contact');
    Route::get('/admin/project/getindex/{get}', 'ProjectController@getindex');

    /*quotation controller
    consist of
    create
    Retrieve
    update
    Delete
    */
    //create form for quotation
    Route::get('/admin/quotation/add', 'QuotationsController@add');
    //store quotation data
    Route::post('/admin/quotation/store', 'QuotationsController@store');
    //retrieve quotations
    Route::get('/admin/quotation', 'QuotationsController@index');
    //retrieve specific quotation
    Route::get('/admin/quotation/{id}', 'QuotationsController@show');
    //edit form for specific quotation
    Route::get('/admin/quotation/{id}/edit', 'QuotationsController@edit');
    //update quotation
    Route::post('/admin/quotation/save', 'QuotationsController@update');
    //delete quotation
    Route::get('/admin/quotation/delete/{id}', 'QuotationsController@destroy');

    /*Contract controller
    consist of
    retrieve
    create
    update
    Delete
    */
    //retrieve contracts
    Route::get('/admin/contract', 'ContractsController@index');
    //display add contract form
    Route::get('/admin/contract/add', 'ContractsController@create');
    //store contract data
    Route::post('/admin/contract/store', 'ContractsController@store');
    //delete contract data
    Route::get('/admin/contract/delete/{id}', 'ContractsController@destroy');
    //retrieve specific contract
    Route::get('/admin/contract/{id}', 'ContractsController@show');
    //edit form for specific contract
    Route::get('/admin/contract/{id}/edit', 'ContractsController@edit');
    //update contract
    Route::post('/admin/contract/save', 'ContractsController@update');

    /*Invoice Controller
    consist of
    retrieve
    create
    update
    Delete
    */
    //retrieve Invoice
    Route::get('/admin/invoice', 'InvoicesController@index');
    //display invoices add form
    Route::get('/admin/invoice/add', 'InvoicesController@create');
    //display invoices based on quotation number
    Route::get('/admin/invoice/{id}', 'InvoicesController@show');
    // Route::post('/admin/invoice', 'InvoicesController@index');
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    //
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Project;
use App\Http\Requests;
use App\Http\Requests\Project\StoreRequest;
use App\Http\Requests\Project\UpdateRequest;
use DB;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::all();
        return view('admin.projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.projects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
		$projects = new Project();
		$projects->konsumen=$request->nama;
		$projects->email=$request->email;
		$projects->hp=$request->phone;
		$projects->deskripsi=$request->deskripsi;
		$projects->status="Prospecting";
        $projects->save();
        return redirect()->route('project.index')->with('alert-success', 'Data Berhasil Disimpan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //$projects = Project::findOrFail($id)->first();
        $projects = Project::find($id);
        return view('admin.projects.edit', compact('projects'));
		//return view('edit')->with('projects',$projects);
	}

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        $projects = Project::findOrFail($id);
		$projects->konsumen=$request->nama;
		$projects->email=$request->email;
		$projects->hp=$request->phone;
		$projects->deskripsi=$request->deskripsi;
        $projects->save();
        return redirect()->route('project.index')->with('alert-success', 'Data Berhasil Diubah.');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $projects = Project::findOrFail($id);
        $projects->delete();
        return redirect()->route('project.index')->with('alert-success', 'Data Berhasil Dihapus.');
    }

	public function contact($id)
	{
		$projects = Project::findOrFail($id);
		$projects->status="Contacted";
        $projects->save();
        return redirect()->route('project.index')->with('alert-success', 'Pelanggan Telah Berhasil Dihubungi.');
	}

	public function getIndex($get){
	  $projects = DB::table('projects');
	  if($get=='aktif'){
		$projects->where('projects.status','Prospecting');
	  }
	  if($get=='non'){
		$projects->where('projects.status','Contacted');
	  }
	  $projects = $projects->paginate(10);
	  return view('projects.index',['projects' => $projects]);
	}

}

resources/views/admin/projects/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h3>ADD Consument</h3>
			<div class="panel panel-default">
				<div class="panel-body">
					<form action="{{route('project.store')}}" method="post">
					{{csrf_field()}}
						<div class="form-group{{ $errors->has('nama') ? ' has-error' : '' }}">
							<label for="nama">Nama</label>
							<input type="text" name="nama" class="form-control" placeholder="Masukan Nama Konsumen" value="{{ old('nama') }}">
							{!! $errors->first('nama', '<p class="help-block">:message</p>') !!}
						</div>
						<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
							<label for="email">Email</label>
							<input type="text" name="email" class="form-control" placeholder="Masukan Email Konsumen" value="{{ old('email') }}">
							{!! $errors->first('email', '<p class="help-block">:message</p>') !!}
						</div>
						<div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
							<label for="phone">Nomor Handphone</label>
							<input type="text" name="phone" class="form-control" placeholder="Nomor Handphone" value="{{ old('phone') }}">
							{!! $errors->first('phone', '<p class="help-block">:message</p>') !!}
						</div>
						<div class="form-group{{ $errors->has('deskripsi') ? ' has-error' : '' }}">
							<label for="deskripsi">Deskripsi</label>
							<textarea name="deskripsi" class="form-control" placeholder="Deskripsi Pyoyek" >{{ old('deskripsi') }}</textarea>
							{!! $errors->first('deskripsi', '<p class="help-block">:message</p>') !!}
						</div>
						<div class="form-group">
							<input type="submit" class="btn btn-primary" value="Simpan">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/projects/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h3>Edit Consument Data</h3>
			<div class="panel panel-default">
				<div class="panel-body">
					<form action="{{route('project.update', $projects->id)}}" method="post">
					<input name="_method" type="hidden" value="PATCH">
					{{csrf_field()}}
						<div class="form-group{{ $errors->has('nama') ? ' has-error' : '' }}">
							<label for="nama">Nama</label>
							<input type="text" name="nama" class="form-control" placeholder="Nama" value="{{$projects->konsumen}}">
							{!! $errors->first('nama', '<p class="help-block">:message</p>') !!}
						</div>
						<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
							<label for="email">Email</label>
							<input type="text" name="email" class="form-control" placeholder="Masukan Email Konsumen" value="{{$projects->email}}">
							{!! $errors->first('email', '<p class="help-block">:message</p>') !!}
						</div>
						<div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
							<label for="phone">Nomor Handphone</label>
							<input type="text" name="phone" class="form-control" placeholder="Nomor Handphone"
							value="{{$projects->hp}}">
							{!! $errors->first('phone', '<p class="help-block">:message</p>') !!}
						</div>
						<div class="form-group{{ $errors->has('deskripsi') ? ' has-error' : '' }}">
							<label for="deskripsi">Deskripsi</label>
							<textarea name="deskripsi" class="form-control" placeholder="Deskripsi Proyek">{{$projects->deskripsi}}</textarea>
							{!! $errors->first('deskripsi', '<p class="help-block">:message</p>') !!}
						</div>
						<div class="form-group">
							<input type="submit" class="btn btn-primary" value="Simpan">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/projects/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h3>Pipeline Project</h3>
			<div class="panel panel-default">
				<div class="panel-body">
					@if(Session::has('alert-success'))
					    <div class="alert alert-success">
				            {{ Session::get('alert-success') }}
				        </div>
					@endif

					<div class="btn-group">

						<button type="button" class="btn btn-info">Filter Status</button>
						<button type="button>" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
						<span class="caret"></span>
						<span class="sr-only">Toggle Dropdown</span>
						</button>
					  <ul class="dropdown-menu">
						<li><a href="{{ url('/admin/project/getindex/'.'aktif')}}">Aktif</a></li>
						<li><a href="{{ url('/admin/project/getindex/'.'non')}}">Non Aktif</a></li>
					  </ul>
					</div>
					<a href="{{route('project.create')}}" class="btn btn-primary pull-right">Tambah Data</a><br><br>

					<table class="table table-bordered">
						<tr>
							<th style="text-align:center;">No</th>
							<th style="text-align:center;">Nama Konsumen</th>
							<th style="text-align:center;">Email</th>
							<th style="text-align:center;">No HP</th>
							<th style="text-align:center;">Deskripsi</th>
							<th style="text-align:center;">Status</th>
							<th style="text-align:center;">Action</th>
						</tr>
						<?php $no=1; ?>
						@foreach($projects->sortBy('status') as $projects)
						<tr>
							<td>{{$no++}}</td>
							<td>{{$projects->konsumen}}</td>
							<td>{{$projects->email}}</td>
							<td>{{$projects->hp}}</td>
							<td>{{$projects->deskripsi}}</td>
							<td>{{$projects->status}}</td>
							<td>
								<form method="POST" action="{{ route('project.destroy', $projects->id) }}" accept-charset="UTF-8">
		                            <input name="_method" type="hidden" value="DELETE">
		                            <input name="_token" type="hidden" value="{{ csrf_token() }}">

									<a href="{{route('project.edit', $projects->id)}}" class="btn btn-primary">Edit</a>
		                        	<input type="submit" class="btn btn-danger" onclick="return confirm('Anda yakin akan menghapus data ?');" value="Delete">

									@if( $projects->status === 'Prospecting')
										<a href="{{url('/admin/project/contact/'.$projects->id)}}" class="btn btn-success">Contact</a>
									@elseif($projects->status === 'Contacted')
										<a href="{{url('/admin/project/contact/'.$projects->id)}}" class="btn btn-info">Discuss</a>
									@endif
		                        </form>
							</td>
						</tr>
						@endforeach
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection